In [ ]:
!nvidia-smi

Tue Nov 19 12:10:05 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.5.1+cu121


In [ ]:
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back to integer
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#vector
vector = torch.tensor([[7, 7],[1, 1]])
vector

tensor([[7, 7],
        [1, 1]])

In [ ]:
vector.ndim

2

In [ ]:
vector.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][1][2]

tensor(6)

In [ ]:
TENSOR1 = torch.tensor([[[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]]])
TENSOR1

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [ ]:
TENSOR1.shape

torch.Size([1, 1, 3, 3])

In [ ]:
TENSOR1[0][0][1][2]

tensor(6)

In [ ]:
#random tensors
random_tensor = torch.rand(2, 2, 2, 2)
random_tensor

tensor([[[[0.1295, 0.2776],
          [0.8581, 0.0185]],

         [[0.0763, 0.4557],
          [0.2615, 0.8967]]],


        [[[0.1639, 0.8523],
          [0.1567, 0.8512]],

         [[0.2007, 0.8562],
          [0.6350, 0.1588]]]])

In [ ]:
random_tensor.ndim

4

In [ ]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor, random_image_tensor.ndim, random_image_tensor.shape

(tensor([[[0.6425, 0.1456, 0.0821],
          [0.9298, 0.3092, 0.9410],
          [0.4393, 0.3279, 0.3289],
          ...,
          [0.5596, 0.5781, 0.9477],
          [0.6705, 0.1407, 0.5008],
          [0.9386, 0.2549, 0.7270]],
 
         [[0.0340, 0.5305, 0.5353],
          [0.5748, 0.0486, 0.7427],
          [0.4710, 0.3493, 0.3349],
          ...,
          [0.8931, 0.2531, 0.7517],
          [0.5964, 0.4117, 0.3149],
          [0.9906, 0.4046, 0.6080]],
 
         [[0.5546, 0.0090, 0.9466],
          [0.1578, 0.8729, 0.0162],
          [0.4958, 0.5557, 0.5759],
          ...,
          [0.5889, 0.1543, 0.6539],
          [0.1547, 0.7822, 0.2255],
          [0.9071, 0.8772, 0.1507]],
 
         ...,
 
         [[0.4520, 0.0306, 0.0091],
          [0.5475, 0.7282, 0.6654],
          [0.2551, 0.6507, 0.3512],
          ...,
          [0.5227, 0.6867, 0.6898],
          [0.9204, 0.3852, 0.6101],
          [0.2593, 0.6024, 0.9306]],
 
         [[0.7891, 0.7674, 0.6316],
          [0

In [ ]:
#tensor of all zeros
zero = torch.zeros(size=(5, 6))
zero

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
#tensor of all ones
ones = torch.ones(size=(2, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#tensors range
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_multiples = torch.arange(start=10, end=101, step=10)
ten_multiples

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
#tensors like
ten_zeros = torch.zeros_like(input=ten_multiples)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_zeros.dtype

torch.int64

In [ ]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this or tensors operations
float_32_tensor

tensor([1., 2., 3.], device='cuda:0')

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

In [ ]:
rd = torch.rand(3, 4)
rd

tensor([[0.3374, 0.2746, 0.3264, 0.1440],
        [0.6727, 0.3163, 0.3216, 0.4931],
        [0.1320, 0.2913, 0.9271, 0.4476]])

In [ ]:
print(f"Datatype: {rd.dtype}")
print(f"Shape: {rd.shape}")
print(f"Device: {rd.device}")

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Tensor Operations

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10  #Addition

tensor([11, 12, 13])

In [ ]:
tensor * 10 #Multiplication

tensor([10, 20, 30])

In [ ]:
tensor - 10 #Subtraction

tensor([-9, -8, -7])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# torch in-built functions
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.div(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
%%time
# element wise matrix multiplication
torch.tensor([1,2,3]) * torch.tensor([4,5,6])

CPU times: user 1.2 ms, sys: 13 µs, total: 1.21 ms
Wall time: 1.02 ms


tensor([ 4, 10, 18])

In [ ]:
torch.matmul(tensor, tensor)  #dot product

tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)  #dot product

CPU times: user 284 µs, sys: 20 µs, total: 304 µs
Wall time: 207 µs


tensor(14)

In [ ]:
%%time
ts = torch.mm(torch.rand(5,10), torch.rand(10,5))     #torch.mm = torch.matmul
ts

CPU times: user 209 µs, sys: 0 ns, total: 209 µs
Wall time: 214 µs


tensor([[2.6521, 3.5381, 3.1103, 2.9716, 2.3433],
        [1.8336, 2.7508, 2.7499, 2.0031, 1.9579],
        [1.0954, 1.9761, 2.3858, 1.1841, 1.8280],
        [2.8329, 2.9609, 2.5682, 2.5147, 2.1253],
        [2.2176, 3.2907, 2.9616, 2.4020, 2.1626]])

In [ ]:
ts.T  #transpose

tensor([[2.6521, 1.8336, 1.0954, 2.8329, 2.2176],
        [3.5381, 2.7508, 1.9761, 2.9609, 3.2907],
        [3.1103, 2.7499, 2.3858, 2.5682, 2.9616],
        [2.9716, 2.0031, 1.1841, 2.5147, 2.4020],
        [2.3433, 1.9579, 1.8280, 2.1253, 2.1626]])

In [ ]:
ts.min()

tensor(1.0954)

In [ ]:
ts.max()

tensor(3.5381)

In [ ]:
ts.mean()

tensor(2.4167)

In [ ]:
ts.sum()

tensor(60.4168)

In [ ]:
ts.argmax()

tensor(1)

In [ ]:
x=torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
z = x_reshaped.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# stack elements on top of each other
x_stack = torch.stack([x,x,x,x], dim=1)
x_stack

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_reshaped = x_reshaped.reshape(1, 9)

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped = x_reshaped.squeeze()  #removes all single dimensions from a tensor

In [ ]:
x_reshaped.shape

torch.Size([9])

In [ ]:
x_reshaped = x_reshaped.unsqueeze(dim=1)  # add a single dimension to the tensor

In [ ]:
x_reshaped.shape

torch.Size([1, 1, 9])

In [ ]:
x_reshaped

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
#torch.permute() # rearranges the dimensions of a tensor in a specified order
img = torch.rand(size=(224, 224, 3))
img_permuted = img.permute(2, 0, 1)

In [ ]:
img_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
# Numpy to Tensor

arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy

tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Reproducibility

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
A = torch.rand(5, 6)

torch.manual_seed(RANDOM_SEED)
B = torch.rand(5, 6)

print(A)
print(B)
print(A==B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])
tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True]])


In [ ]:
# Check for GPU if available
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')